services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    networks:
      - stdf-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - stdf-net

networks:
  stdf-net:
    driver: bridge
